language: go

go:
 - 1.4
 - 1.5

env:
 - PUBLISH_VERSION=1.5

services:
 - docker

after_success:
 - test "$PUBLISH_VERSION" == "$TRAVIS_GO_VERSION" && docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - test "$PUBLISH_VERSION" == "$TRAVIS_GO_VERSION" && make publish-docker
